name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - run: npm install -g typescript
      - run: tsc
      - run: git config --global user.email "luigi.donadel@gmail.com"
      - run: git config --global user.name "donadev"
      - run: git remote set-url --push origin https://donadev:$GITHUB_TOKEN@github.com/donadev/TicTacToe
      - run: git commit -am "Built" && git push
