name: reload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - run: node index.js
      - run: git remote set-url --push origin https://donadev:$GITHUB_TOKEN@github.com/your/repo
      - run: git commit -m "Refreshed output" & git push
